apiVersion: apps/v1
kind: Deployment
metadata:
  name: myeconomics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myeconomics
  template:
    metadata:
      labels:
        app: myeconomics
    spec:
      containers:
        - image: maravelias/myeconomics
          imagePullPolicy: IfNotPresent
          name: myeconomics
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: myeconomics-db-config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myeconomics-db-config
                  key: db_password
            - name: DB_HOST
              value: myeconomics-db-service
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: HZ_NETWORK_JOIN_KUBERNETES_ENABLED
              value: "true"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 8080
            - containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: myeconomics-service
spec:
  type: NodePort
  ports:
    - port: 8080
      name: myeconomics-app
    - port: 5701
      name: myeconomics-hazelcast
  selector:
    app: myeconomics