---
apiVersion: v1
kind: Service
metadata:
  name: myeconomics-app-service
  namespace: myeconomics
spec:
  ports:
    - name: web8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: myeconomics-app
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: myeconomics
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer